package model

case class Student (
                      name: String,
                      age: String,
                      gender: String,
                      birthCity: String,
                      birthCountry: String,
                      siblings: String,
                      bachelor: String,
                      bachelorLocation: String,
                      master: String,
                      phd: String,
                      faoriteSport: String,
                      favoriteMusic: String,
                      favoriteBook: String,
                      favoriteGame: String,
                      favoriteFood: String,
                      favoritCar: String,
                      favoriteMovie: String,
                      favoriteActor: String,
                      favoriteCity: String,
                      favoriteCanadianCity: String,
                      yearIT: String,
                      language: String,
                      hourDailyStudy: String,
                      hourDailyRest: String,
                      hourDailySports: String,
                      hourDailyWorks: String,
                      hourDailySleep: String,
                      spokenLanguageCount: String,
                      favoriteColor: String,
                      isWatchPolitics: String, //Boolean,
                      isprofessionalSavvy: String, //Boolean,
                      isGoodAtSQL : String, //Boolean,
                      isGoodAtCloud: String, //Boolean,
                      isGoodAtHadoop: String, //Boolean,
                      isGoodAtNoSQL: String, //ring, //Boolean,
                      isUsingLinkedInLinkedin: String, //Boolean,
                      linkedinContactsCount: String,
                      hasJobInterviews: String //Boolean
                    )